### ISSUE TITLE
[1.3.4] Doesn't show news

### ISSUE THREAD

**Issue by AircraftRu** [pluginsGLPI/news#42] opened 2017-09-27 09:22 UTC
Hello,
Plugin doesn't show news, more below.

GLPI 9.2

**Comment by flegastelois** [comment] 2017-10-24 15:47
Hi @AircraftRu 

I can't reproduce your problem, with a target "group" I have the alert displayed.
Do you have more details? Errors ?

Regards,

**Comment by AircraftRu** [comment] 2017-11-03 11:42
Hi @flegastelois 
The target of group:
![glpi - alerts - target of groups](https://user-images.githubusercontent.com/17082164/32372216-f78216d0-c0a4-11e7-8cac-504b61527ab2.png)
In 9.1 I see the alert, in 9.2 I don't see the alert.

**Comment by AircraftRu** [comment] 2017-12-27 09:34
I found new problems.
When I open the alert first I see:
no edit tools, style not correct

![glpi - alerts - 5 - mozilla firefox 2017-12-27 11 25 37](https://user-images.githubusercontent.com/17082164/34376634-c8d82094-eafd-11e7-838e-0c1af6add5e0.png)

After reflesh:

![glpi - alerts - 5 - mozilla firefox 2017-12-27 11 26 09](https://user-images.githubusercontent.com/17082164/34376687-34226986-eafe-11e7-86f7-b3a4fbe2be8c.png)

**Comment by AircraftRu** [comment] 2018-02-07 12:23
Hello! 
When will you be solving this issue?

I'm getting this error:
```
2018-02-06 12:51:11 Europe/Moscow [139@glpi]
  *** PHP Notice(8): Undefined index: entities_id
  Backtrace :
  plugins/news/inc/alert.class.php:498               
  inc/plugin.class.php:1271                          PluginNewsAlert::preItemForm()
  inc/ticket.class.php:3899                          Plugin::doHook()
  front/tracking.injector.php:97                     Ticket->showFormHelpdesk()
```

**Comment by AircraftRu** [comment] 2018-02-07 12:51
I also noticed that depends on entities and sub-entities. In 9.1.4 (plugin 1.3.2.5) is all right.

**Comment by AircraftRu** [comment] 2018-03-02 06:42
Hello! Does somebody support the plugin?

**Comment by flegastelois** [comment] 2018-05-11 09:58
Hi @AircraftRu ,

The community support of this plugin is made in best-effort, if you want to contribute I invite you to follow the developer documentation and make pull-request : https://github.com/pluginsGLPI/news#contributing

If you want professional support, you can contact one of our GLPI Network partners program : http://glpi-project.org/partners/

Finally, some of your problems will be solved in the next release.
1. The problem with rich text editor that shows only on refresh should be solved by this commit : https://github.com/pluginsGLPI/news/commit/54b2acf7688bfc897d9bc47f8896a15b5eff07ac
2. The Undefined index: entities_id notice should be solved by this commit : https://github.com/pluginsGLPI/news/commit/9391707163b7f538266795db17ad3a2d59d15a59
3. Entity management on alerts (entities+child-entities dropdown) will be removed in favor of a new target "Entity"

So, I advise you to wait until this version is out, certainly by this summer.

Regards,

**Comment by stonebuzz** [comment] 2020-01-23 09:44
Hi @AircraftRu 

This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards

**Closed by stonebuzz** 2020-01-23 09:44 UTC
Labels: wontfix
